# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShorelineSEPlus
                                 A QGIS plugin
 Semi-automated shoreline extraction from multispectral imagery using MNDWI, robust Otsu thresholding, cleanup, smoothing, and Processing outputs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by Curtis Amo Dwira
        email                : amodwira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Curtis Amo Dwira'
__date__ = '2026-03-20'
__copyright__ = '(C) 2026 by Curtis Amo Dwira'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShorelineSEPlus class from file ShorelineSEPlus.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .shoreline_seplus import ShorelineSEPlus
    return ShorelineSEPlus(iface)