# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ShorelineSEPlus
                                 A QGIS plugin
 Semi-automated shoreline extraction from multispectral imagery using MNDWI, robust Otsu thresholding, cleanup, smoothing, and Processing outputs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by Curtis Amo Dwira
        email                : amodwira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Curtis Amo Dwira'
__date__ = '2026-03-20'
__copyright__ = '(C) 2026 by Curtis Amo Dwira'

__revision__ = '$Format:%H$'

from qgis.core import QgsApplication
from .shoreline_seplus_provider import ShorelineSEPlusProvider


class ShorelineSEPlus:
    def __init__(self, iface):
        self.iface = iface
        self.provider = None

    def initProcessing(self):
        if self.provider is None:
            self.provider = ShorelineSEPlusProvider()
            QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        if self.provider is not None:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None