# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ShorelineSEPlus
                                 A QGIS plugin
 Semi-automated shoreline extraction from multispectral imagery using MNDWI, robust Otsu thresholding, cleanup, smoothing, and Processing outputs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by Curtis Amo Dwira
        email                : amodwira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Curtis Amo Dwira'
__date__ = '2026-03-20'
__copyright__ = '(C) 2026 by Curtis Amo Dwira'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

# -*- coding: utf-8 -*-
"""
***************************************************************************
* Shoreline SE+ — QGIS Processing Algorithm
*
* Features:
* - optional study area clipping
* - autoscale reflectance
* - robust Otsu thresholding (0.5–99.5% clip)
* - lightweight raster smoothing
* - ocean-connected water selection
* - hole/speckle cleanup on water polygons
* - polygon smoothing before shoreline conversion
* - border trimming using line difference against buffered boundary
* - reduced fragment filtering to preserve connectors
* - SEG_ID on raw, smoothed, and final outputs
* - metadata JSON
* - outputs added to QGIS map interface
* - internal metric CRS for all area/length/buffer operations
***************************************************************************
"""

from typing import Any, Optional
import os
import json
import math
import datetime
import numpy as np
from osgeo import gdal

from qgis.core import (
    QgsProject,
    QgsField,
    QgsVectorLayer,
    QgsRasterLayer,
    QgsCoordinateTransform,
    QgsCoordinateReferenceSystem,
    QgsPointXY,
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingContext,
    QgsProcessingException,
    QgsProcessingFeedback,
    QgsProcessingUtils,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterBand,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFolderDestination,
    QgsProcessingParameterString,
    QgsProcessingParameterCrs,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterVectorDestination,
)
from qgis.PyQt.QtCore import QVariant, QCoreApplication
from qgis import processing


# -----------------------
# Helpers
# -----------------------

def _delete_dataset_if_exists(path: str):
    if not path:
        return

    if path in ("memory:", "TEMPORARY_OUTPUT"):
        return

    base, ext = os.path.splitext(path)
    ext = ext.lower()

    try:
        if ext == ".shp":
            for sfx in [".shp", ".shx", ".dbf", ".prj", ".cpg", ".qpj", ".sbn", ".sbx"]:
                p = base + sfx
                if os.path.exists(p):
                    os.remove(p)
        else:
            if os.path.exists(path):
                os.remove(path)
    except Exception:
        pass


def _autoscale(arr: np.ndarray) -> np.ndarray:
    finite = arr[np.isfinite(arr)]
    if finite.size == 0:
        return arr
    p99 = np.nanpercentile(finite, 99)
    return arr / 10000.0 if p99 > 10 else arr


def _clip_percentiles(a: np.ndarray, lo=0.5, hi=99.5):
    finite = a[np.isfinite(a)]
    if finite.size == 0:
        return a, None, None
    low, high = np.nanpercentile(finite, [lo, hi])
    return np.clip(a, low, high), float(low), float(high)


def _otsu_threshold(array: np.ndarray) -> float:
    data = array[np.isfinite(array)]
    if data.size == 0:
        return 0.0

    hist, bin_edges = np.histogram(data, bins=256)

    total = data.size
    sum_total = np.dot(hist, bin_edges[:-1])

    sumB = 0.0
    wB = 0.0
    max_var = 0.0
    threshold = 0.0

    for i in range(len(hist)):
        wB += hist[i]
        if wB == 0:
            continue

        wF = total - wB
        if wF == 0:
            break

        sumB += bin_edges[i] * hist[i]
        mB = sumB / wB
        mF = (sum_total - sumB) / wF
        var_between = wB * wF * (mB - mF) ** 2

        if var_between > max_var:
            max_var = var_between
            threshold = bin_edges[i]

    return float(threshold)


def _simple_smooth(arr: np.ndarray) -> np.ndarray:
    nan_mask = ~np.isfinite(arr)
    work = np.nan_to_num(arr, nan=0.0)

    smooth = (
        work
        + np.roll(work, 1, axis=0)
        + np.roll(work, -1, axis=0)
        + np.roll(work, 1, axis=1)
        + np.roll(work, -1, axis=1)
    ) / 5.0

    smooth[nan_mask] = np.nan
    return smooth


def _save_array_as_gtiff(path, arr, ref_ds, gdal_type, nodata=None):
    _delete_dataset_if_exists(path)
    driver = gdal.GetDriverByName("GTiff")
    out_ds = driver.Create(path, ref_ds.RasterXSize, ref_ds.RasterYSize, 1, gdal_type)
    out_ds.SetGeoTransform(ref_ds.GetGeoTransform())
    out_ds.SetProjection(ref_ds.GetProjection())
    band = out_ds.GetRasterBand(1)
    band.WriteArray(arr)
    if nodata is not None:
        band.SetNoDataValue(nodata)
    band.FlushCache()
    out_ds.FlushCache()
    out_ds = None


def _detect_value_field(vlayer: QgsVectorLayer) -> str:
    candidates = ["DN", "GRIDCODE", "VALUE", "GRID_CODE"]
    fields = [f.name() for f in vlayer.fields()]
    upper_map = {f.upper(): f for f in fields}

    for c in candidates:
        if c in upper_map:
            return upper_map[c]

    for f in vlayer.fields():
        if f.typeName().lower() in ("integer", "int", "real", "double", "smallint"):
            return f.name()

    return fields[0] if fields else "DN"


def _estimate_projected_pixel_size(raster_layer: QgsRasterLayer, dst_crs) -> float:
    src_crs = raster_layer.crs()
    ds = gdal.Open(raster_layer.source())
    if ds is None:
        return 1.0

    gt = ds.GetGeoTransform()
    px = abs(gt[1]) if gt else 1.0

    if not src_crs.isValid() or not dst_crs.isValid() or src_crs == dst_crs:
        return px

    try:
        ext = raster_layer.extent()
        cx = (ext.xMinimum() + ext.xMaximum()) / 2.0
        cy = (ext.yMinimum() + ext.yMaximum()) / 2.0

        tr = QgsCoordinateTransform(src_crs, dst_crs, QgsProject.instance())
        p1 = tr.transform(QgsPointXY(cx, cy))
        p2 = tr.transform(QgsPointXY(cx + px, cy))

        dist = ((p2.x() - p1.x()) ** 2 + (p2.y() - p1.y()) ** 2) ** 0.5
        return dist if dist > 0 else px
    except Exception:
        return px


def _as_vector_layer(obj, context: QgsProcessingContext, name="layer"):
    if isinstance(obj, QgsVectorLayer):
        return obj

    if isinstance(obj, str):
        lyr = QgsProcessingUtils.mapLayerFromString(obj, context)
        if isinstance(lyr, QgsVectorLayer):
            return lyr

        if os.path.exists(obj):
            v = QgsVectorLayer(obj, name, "ogr")
            if v.isValid():
                return v

    return None


def _add_seg_id_any(target, context: Optional[QgsProcessingContext] = None):
    layer = None

    if context is not None:
        layer = _as_vector_layer(target, context, "seg_layer")

    if layer is None and isinstance(target, str) and os.path.exists(target):
        layer = QgsVectorLayer(target, "seg_layer", "ogr")

    if layer is None or not layer.isValid():
        return

    field_names = [f.name().upper() for f in layer.fields()]
    if "SEG_ID" in field_names:
        return

    if not layer.isEditable():
        layer.startEditing()

    layer.dataProvider().addAttributes([QgsField("SEG_ID", QVariant.Int)])
    layer.updateFields()
    idx = layer.fields().indexFromName("SEG_ID")

    for i, feat in enumerate(layer.getFeatures(), start=1):
        layer.changeAttributeValue(feat.id(), idx, i)

    layer.commitChanges()


def _drop_pk_like_fields(layer_input, context, feedback=None):
    vlayer = _as_vector_layer(layer_input, context, "drop_pk_src")
    if vlayer is None or not vlayer.isValid():
        return layer_input

    field_names = [f.name() for f in vlayer.fields()]
    drop_names_upper = {"FID", "OGC_FID"}

    if not any(name.upper() in drop_names_upper for name in field_names):
        return layer_input

    if feedback:
        removed = [n for n in field_names if n.upper() in drop_names_upper]
        feedback.pushInfo(f"Removing primary-key-like fields before save: {removed}")

    field_mapping = []
    for f in vlayer.fields():
        if f.name().upper() in drop_names_upper:
            continue

        field_mapping.append({
            "expression": f"\"{f.name()}\"",
            "name": f.name(),
            "type": f.type(),
            "length": f.length(),
            "precision": f.precision(),
        })

    cleaned = processing.run(
        "native:refactorfields",
        {
            "INPUT": layer_input,
            "FIELDS_MAPPING": field_mapping,
            "OUTPUT": "memory:"
        },
        context=context,
        feedback=feedback
    )["OUTPUT"]

    return cleaned


def _queue_layer_for_loading(
    layer_source: str,
    layer_name: str,
    context: QgsProcessingContext,
    output_name: str = "",
    group_name: str = "SE+ Outputs",
    sort_key: int = 0,
):
    if not layer_source:
        return

    project = context.project() if context.project() else QgsProject.instance()
    details = QgsProcessingContext.LayerDetails(layer_name, project, output_name)
    details.forceName = True
    details.groupName = group_name
    details.layerSortKey = sort_key
    context.addLayerToLoadOnCompletion(layer_source, details)


def _get_band_description(ds, band_index: int) -> str:
    try:
        b = ds.GetRasterBand(band_index)
        if b is None:
            return f"Band {band_index}"
        desc = b.GetDescription()
        return desc if desc else f"Band {band_index}"
    except Exception:
        return f"Band {band_index}"


def _pick_metric_working_crs(raster_layer: QgsRasterLayer, preferred_crs) -> QgsCoordinateReferenceSystem:
    if preferred_crs.isValid() and not preferred_crs.isGeographic():
        return preferred_crs

    src_crs = raster_layer.crs()
    ext = raster_layer.extent()
    cx = (ext.xMinimum() + ext.xMaximum()) / 2.0
    cy = (ext.yMinimum() + ext.yMaximum()) / 2.0

    try:
        if src_crs.authid() != "EPSG:4326":
            tr = QgsCoordinateTransform(src_crs, QgsCoordinateReferenceSystem("EPSG:4326"), QgsProject.instance())
            p = tr.transform(QgsPointXY(cx, cy))
            lon = p.x()
            lat = p.y()
        else:
            lon = cx
            lat = cy
    except Exception:
        lon = cx
        lat = cy

    zone = int(math.floor((lon + 180.0) / 6.0) + 1)
    zone = max(1, min(zone, 60))

    epsg = 32600 + zone if lat >= 0 else 32700 + zone
    crs = QgsCoordinateReferenceSystem.fromEpsgId(epsg)

    if crs.isValid():
        return crs

    fallback = QgsCoordinateReferenceSystem("EPSG:32615")
    return fallback if fallback.isValid() else preferred_crs


class ShorelineSEPlusAlgorithm(QgsProcessingAlgorithm):

    INPUT = "INPUT"
    GREEN_BAND = "GREEN_BAND"
    SWIR_BAND = "SWIR_BAND"
    STUDY_AREA = "STUDY_AREA"
    OUTPUT_FOLDER = "OUTPUT_FOLDER"
    PREFIX = "PREFIX"
    CRS = "CRS"
    DROP_BORDER = "DROP_BORDER"
    OUTPUT = "OUTPUT"

    def tr(self, string):
        return QCoreApplication.translate("Processing", string)

    def createInstance(self):
        return ShorelineSEPlusAlgorithm()

    def name(self):
        return "shoreline_extractor_seplus_v28"

    def displayName(self):
        return self.tr("Shoreline Extractor (SE+ QGIS)")

    def group(self):
        return self.tr("Shoreline Tools")

    def groupId(self):
        return "shoreline_tools"

    def shortHelpString(self):
        return self.tr(
            "SE+ v2.8 shoreline extraction using MNDWI + robust Otsu, "
            "ocean-only filtering, polygon cleanup, polygon smoothing, "
            "border trimming, preserved connectors, SEG_ID, metadata JSON, "
            "automatic map loading, and internal metric CRS processing."
        )

    def initAlgorithm(self, config: Optional[dict[str, Any]] = None):

        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr("Composite Raster")
            )
        )

        self.addParameter(
            QgsProcessingParameterBand(
                self.GREEN_BAND,
                self.tr("Green Band"),
                parentLayerParameterName=self.INPUT,
                defaultValue=3
            )
        )

        self.addParameter(
            QgsProcessingParameterBand(
                self.SWIR_BAND,
                self.tr("SWIR Band"),
                parentLayerParameterName=self.INPUT,
                defaultValue=6
            )
        )

        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.STUDY_AREA,
                self.tr("Study Area (optional)"),
                [QgsProcessing.TypeVectorPolygon],
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                self.OUTPUT_FOLDER,
                self.tr("Output Folder")
            )
        )

        self.addParameter(
            QgsProcessingParameterString(
                self.PREFIX,
                self.tr("Output File Prefix")
            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                self.CRS,
                self.tr("Output Coordinate System")
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.DROP_BORDER,
                self.tr("Remove study-area/extent border segments"),
                defaultValue=True
            )
        )

        self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT,
                self.tr("Shoreline Output")
            )
        )

    def processAlgorithm(self, parameters, context: QgsProcessingContext, feedback: QgsProcessingFeedback):

        raster = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        green_band_index = self.parameterAsInt(parameters, self.GREEN_BAND, context)
        swir_band_index = self.parameterAsInt(parameters, self.SWIR_BAND, context)
        study_area = self.parameterAsSource(parameters, self.STUDY_AREA, context)
        output_folder = self.parameterAsString(parameters, self.OUTPUT_FOLDER, context)
        prefix = self.parameterAsString(parameters, self.PREFIX, context)
        output_crs = self.parameterAsCrs(parameters, self.CRS, context)
        drop_border = self.parameterAsBool(parameters, self.DROP_BORDER, context)

        if raster is None:
            raise QgsProcessingException("Invalid raster input.")

        if not output_crs.isValid():
            output_crs = raster.crs()

        working_crs = _pick_metric_working_crs(raster, output_crs)

        os.makedirs(output_folder, exist_ok=True)

        comp_path = raster.source()
        comp_sr = raster.crs()

        feedback.pushInfo(f"Raster: {comp_path} | CRS: {comp_sr.authid()}")
        feedback.pushInfo(f"Requested output CRS: {output_crs.authid() if output_crs.isValid() else 'None'}")
        feedback.pushInfo(f"Internal metric working CRS: {working_crs.authid() if working_crs.isValid() else 'None'}")

        clipped_path = os.path.join(output_folder, f"{prefix}_clipped.tif")
        mndwi_raster_path = os.path.join(output_folder, f"{prefix}_mndwi.tif")
        binary_raster_path = os.path.join(output_folder, f"{prefix}_binary.tif")
        polygon_path = os.path.join(output_folder, f"{prefix}_water_polygon.gpkg")
        fixed_polygon_path = os.path.join(output_folder, f"{prefix}_water_polygon_fixed.gpkg")
        raw_segments_path = os.path.join(output_folder, f"{prefix}_shoreline_raw_metric.gpkg")
        smoothed_metric_path = os.path.join(output_folder, f"{prefix}_shoreline_smoothed_metric.gpkg")
        projected_study_area = os.path.join(output_folder, f"{prefix}_projected_study_area.gpkg")
        mask_boundary = os.path.join(output_folder, f"{prefix}_mask_boundary.gpkg")
        extent_fc = os.path.join(output_folder, f"{prefix}_raster_extent.gpkg")
        metadata_path = os.path.join(output_folder, f"{prefix}_metadata.json")

        for p in [
            clipped_path, mndwi_raster_path, binary_raster_path, polygon_path,
            fixed_polygon_path, raw_segments_path, smoothed_metric_path,
            projected_study_area, mask_boundary, extent_fc, metadata_path
        ]:
            _delete_dataset_if_exists(p)

        raster_path = comp_path
        raster_layer_for_extent = raster

        if study_area:
            try:
                feedback.pushInfo("Reprojecting study area to raster CRS.")
                projected_study_area = processing.run(
                    "native:reprojectlayer",
                    {
                        "INPUT": parameters[self.STUDY_AREA],
                        "TARGET_CRS": comp_sr,
                        "OUTPUT": projected_study_area
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                feedback.pushInfo("Clipping raster to study area.")
                raster_path = processing.run(
                    "gdal:cliprasterbymasklayer",
                    {
                        "INPUT": comp_path,
                        "MASK": projected_study_area,
                        "CROP_TO_CUTLINE": True,
                        "KEEP_RESOLUTION": True,
                        "OUTPUT": clipped_path
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                raster_layer_for_extent = QgsRasterLayer(raster_path, f"{prefix}_clipped")
            except Exception as e:
                feedback.reportError(f"Study area project/clip failed, using full raster: {e}")
                raster_path = comp_path
                raster_layer_for_extent = raster

        ds = gdal.Open(str(raster_path))
        if ds is None:
            raise QgsProcessingException("Could not open raster after clipping.")

        green_desc = _get_band_description(ds, green_band_index)
        swir_desc = _get_band_description(ds, swir_band_index)
        feedback.pushInfo(
            f"Selected bands -> Green index {green_band_index} [{green_desc}], "
            f"SWIR index {swir_band_index} [{swir_desc}]"
        )

        green = _autoscale(ds.GetRasterBand(green_band_index).ReadAsArray().astype(float))
        swir = _autoscale(ds.GetRasterBand(swir_band_index).ReadAsArray().astype(float))

        gt = ds.GetGeoTransform()
        cs = abs(gt[1]) if gt and gt[1] != 0 else 1.0

        if cs <= 0.5:
            gaussian_sigma = 2.0
        elif cs <= 2:
            gaussian_sigma = 1.5
        elif cs <= 10:
            gaussian_sigma = 1.0
        elif cs <= 30:
            gaussian_sigma = 0.7
        else:
            gaussian_sigma = 0.5

        morph_radius = max(1, int(round(gaussian_sigma)))
        feedback.pushInfo(f"Detected raster cell size (map units): {cs}")
        feedback.pushInfo(f"Auto params: sigma={gaussian_sigma}, morph_radius={morph_radius}")

        proj_pixel = _estimate_projected_pixel_size(raster_layer_for_extent, working_crs)

        min_hole_area = max((proj_pixel ** 2) * 8.0, 900.0)
        min_poly_area = max((proj_pixel ** 2) * 12.0, 1200.0)
        min_fragment_length = max(proj_pixel * 1.0, 8.0)
        border_buffer_dist = max(proj_pixel * 0.60, 3.0)

        if proj_pixel <= 5:
            poly_smooth_iterations = 2
            poly_smooth_offset = 0.15
            line_smooth_iterations = 1
            line_smooth_offset = 0.12
        elif proj_pixel <= 15:
            poly_smooth_iterations = 2
            poly_smooth_offset = 0.18
            line_smooth_iterations = 1
            line_smooth_offset = 0.14
        elif proj_pixel <= 30:
            poly_smooth_iterations = 3
            poly_smooth_offset = 0.22
            line_smooth_iterations = 2
            line_smooth_offset = 0.16
        else:
            poly_smooth_iterations = 3
            poly_smooth_offset = 0.25
            line_smooth_iterations = 2
            line_smooth_offset = 0.18

        feedback.pushInfo(
            f"Metric pixel size: {proj_pixel:.4f} | "
            f"min_hole_area={min_hole_area:.2f}, "
            f"min_poly_area={min_poly_area:.2f}, "
            f"min_fragment_length={min_fragment_length:.2f}, "
            f"border_buffer={border_buffer_dist:.2f}"
        )
        feedback.pushInfo(
            f"Polygon smoothing -> iterations={poly_smooth_iterations}, offset={poly_smooth_offset:.2f} | "
            f"Line smoothing -> iterations={line_smooth_iterations}, offset={line_smooth_offset:.2f}"
        )

        mndwi = (green - swir) / (green + swir + 1e-10)
        mndwi = _simple_smooth(mndwi)

        finite_mask = np.isfinite(mndwi)
        finite_vals = mndwi[finite_mask]
        if finite_vals.size == 0:
            raise QgsProcessingException("MNDWI array has no valid data to threshold.")

        clipped_vals, lo_p, hi_p = _clip_percentiles(finite_vals, 0.5, 99.5)
        thresh = _otsu_threshold(clipped_vals)
        feedback.pushInfo(f"Otsu threshold (robust): {thresh:.6f} (clip {lo_p:.4f}–{hi_p:.4f})")

        binary_bool = mndwi > thresh
        water_count = int(np.sum(np.logical_and(binary_bool, finite_mask)))
        feedback.pushInfo(f"Water pixel count: {water_count}")

        if water_count == 0:
            raise QgsProcessingException("No water pixels detected. Check bands, clipping, or scene quality.")

        binary_bool = _simple_smooth(binary_bool.astype(float)) > 0.5

        _save_array_as_gtiff(
            mndwi_raster_path,
            np.nan_to_num(mndwi, nan=-9999).astype(np.float32),
            ds,
            gdal.GDT_Float32,
            -9999
        )

        binary_uint8 = np.full_like(mndwi, 255, dtype=np.uint8)
        binary_uint8[finite_mask] = binary_bool[finite_mask].astype(np.uint8)

        _save_array_as_gtiff(
            binary_raster_path,
            binary_uint8,
            ds,
            gdal.GDT_Byte,
            255
        )

        feedback.pushInfo(f"MNDWI saved: {mndwi_raster_path}")
        feedback.pushInfo(f"Binary saved: {binary_raster_path}")

        polygon = processing.run(
            "gdal:polygonize",
            {
                "INPUT": binary_raster_path,
                "BAND": 1,
                "OUTPUT": polygon_path
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        polygon = processing.run(
            "native:fixgeometries",
            {
                "INPUT": polygon,
                "OUTPUT": fixed_polygon_path
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        polygon_layer = QgsVectorLayer(polygon, "water_polygon", "ogr")
        if not polygon_layer.isValid():
            raise QgsProcessingException("Polygonized layer could not be opened.")

        value_field = _detect_value_field(polygon_layer)
        feedback.pushInfo(f"Polygon value field detected: {value_field}")

        valid_polygons = processing.run(
            "native:extractbyexpression",
            {
                "INPUT": polygon,
                "EXPRESSION": f"\"{value_field}\" = 1",
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        feedback.pushInfo("Water polygons isolated.")

        try:
            if study_area and projected_study_area:
                mask_boundary = processing.run(
                    "qgis:polygonstolines",
                    {
                        "INPUT": projected_study_area,
                        "OUTPUT": mask_boundary
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]
                feedback.pushInfo("Mask boundary from study area created.")
            else:
                extent_fc = processing.run(
                    "native:polygonfromlayerextent",
                    {
                        "INPUT": raster_layer_for_extent,
                        "OUTPUT": extent_fc
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                mask_boundary = processing.run(
                    "qgis:polygonstolines",
                    {
                        "INPUT": extent_fc,
                        "OUTPUT": mask_boundary
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]
                feedback.pushInfo("Mask boundary from raster extent created.")
        except Exception as e:
            feedback.reportError(f"Failed to create mask boundary: {e}")
            mask_boundary = None

        try:
            ocean_candidates = valid_polygons

            if mask_boundary:
                ocean_candidates = processing.run(
                    "native:extractbylocation",
                    {
                        "INPUT": valid_polygons,
                        "PREDICATE": [0],
                        "INTERSECT": mask_boundary,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                oc_layer = _as_vector_layer(ocean_candidates, context, "ocean_candidates")
                if oc_layer is None or oc_layer.featureCount() == 0:
                    feedback.reportError("No boundary-touching water found; falling back to all water polygons.")
                    ocean_candidates = valid_polygons

            ocean_candidates_metric = processing.run(
                "native:reprojectlayer",
                {
                    "INPUT": ocean_candidates,
                    "TARGET_CRS": working_crs,
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]

            main_water_metric = processing.run(
                "native:extractbyexpression",
                {
                    "INPUT": ocean_candidates_metric,
                    "EXPRESSION": "$area = maximum($area)",
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]

            main_water_metric = processing.run(
                "native:fixgeometries",
                {
                    "INPUT": main_water_metric,
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]

            oc_layer = _as_vector_layer(main_water_metric, context, "main_water_metric")
            if oc_layer and oc_layer.featureCount() > 0:
                best_area = max(feat.geometry().area() for feat in oc_layer.getFeatures())
                feedback.pushInfo(f"Ocean water selected (metric area={best_area:.2f}).")

            valid_polygons = main_water_metric

            if mask_boundary:
                mask_boundary = processing.run(
                    "native:reprojectlayer",
                    {
                        "INPUT": mask_boundary,
                        "TARGET_CRS": working_crs,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

        except Exception as e:
            feedback.reportError(f"Ocean-only filtering failed; continuing with all water polygons: {e}")

            valid_polygons = processing.run(
                "native:reprojectlayer",
                {
                    "INPUT": valid_polygons,
                    "TARGET_CRS": working_crs,
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]

            valid_polygons = processing.run(
                "native:fixgeometries",
                {
                    "INPUT": valid_polygons,
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]

            if mask_boundary:
                mask_boundary = processing.run(
                    "native:reprojectlayer",
                    {
                        "INPUT": mask_boundary,
                        "TARGET_CRS": working_crs,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

        valid_polygons = processing.run(
            "native:deleteholes",
            {
                "INPUT": valid_polygons,
                "MIN_AREA": min_hole_area,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        valid_polygons = processing.run(
            "native:multiparttosingleparts",
            {
                "INPUT": valid_polygons,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        valid_polygons = processing.run(
            "native:extractbyexpression",
            {
                "INPUT": valid_polygons,
                "EXPRESSION": f"$area >= {min_poly_area}",
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        valid_polygons = processing.run(
            "native:dissolve",
            {
                "INPUT": valid_polygons,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        valid_polygons = processing.run(
            "native:fixgeometries",
            {
                "INPUT": valid_polygons,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        smoothed_water_poly = processing.run(
            "native:smoothgeometry",
            {
                "INPUT": valid_polygons,
                "ITERATIONS": poly_smooth_iterations,
                "OFFSET": poly_smooth_offset,
                "MAX_ANGLE": 180,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        smoothed_water_poly = processing.run(
            "native:fixgeometries",
            {
                "INPUT": smoothed_water_poly,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        shoreline_lines = processing.run(
            "qgis:polygonstolines",
            {
                "INPUT": smoothed_water_poly,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        shoreline_lines = processing.run(
            "native:multiparttosingleparts",
            {
                "INPUT": shoreline_lines,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        shoreline_lines = processing.run(
            "native:fixgeometries",
            {
                "INPUT": shoreline_lines,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        if drop_border and mask_boundary:
            try:
                boundary_buffer = processing.run(
                    "native:buffer",
                    {
                        "INPUT": mask_boundary,
                        "DISTANCE": border_buffer_dist,
                        "SEGMENTS": 5,
                        "END_CAP_STYLE": 0,
                        "JOIN_STYLE": 0,
                        "MITER_LIMIT": 2,
                        "DISSOLVE": True,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                shoreline_lines = processing.run(
                    "native:difference",
                    {
                        "INPUT": shoreline_lines,
                        "OVERLAY": boundary_buffer,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                shoreline_lines = processing.run(
                    "native:multiparttosingleparts",
                    {
                        "INPUT": shoreline_lines,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                shoreline_lines = processing.run(
                    "native:fixgeometries",
                    {
                        "INPUT": shoreline_lines,
                        "OUTPUT": "memory:"
                    },
                    context=context,
                    feedback=feedback
                )["OUTPUT"]

                feedback.pushInfo("Removed border-touching shoreline portions using line difference.")
            except Exception as e:
                feedback.reportError(f"Border trimming failed; continuing without border trim: {e}")

        shoreline_lines = processing.run(
            "native:extractbyexpression",
            {
                "INPUT": shoreline_lines,
                "EXPRESSION": f"$length >= {min_fragment_length}",
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        shoreline_lines = processing.run(
            "native:fixgeometries",
            {
                "INPUT": shoreline_lines,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        raw_lines_clean = _drop_pk_like_fields(shoreline_lines, context, feedback)

        _delete_dataset_if_exists(raw_segments_path)
        raw_segments_saved = processing.run(
            "native:savefeatures",
            {
                "INPUT": raw_lines_clean,
                "OUTPUT": raw_segments_path
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        raw_layer = QgsVectorLayer(raw_segments_saved, "shoreline_raw_metric", "ogr")
        raw_count = raw_layer.featureCount() if raw_layer.isValid() else 0
        feedback.pushInfo(f"Raw shoreline features after cleanup: {raw_count}")

        _delete_dataset_if_exists(smoothed_metric_path)
        smoothed_metric = processing.run(
            "native:smoothgeometry",
            {
                "INPUT": raw_segments_saved,
                "ITERATIONS": line_smooth_iterations,
                "OFFSET": line_smooth_offset,
                "MAX_ANGLE": 180,
                "OUTPUT": smoothed_metric_path
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        smoothed_metric = processing.run(
            "native:fixgeometries",
            {
                "INPUT": smoothed_metric,
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        smoothed_metric = processing.run(
            "native:extractbyexpression",
            {
                "INPUT": smoothed_metric,
                "EXPRESSION": f"$length >= {min_fragment_length}",
                "OUTPUT": "memory:"
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        smoothed_metric_clean = _drop_pk_like_fields(smoothed_metric, context, feedback)

        final_destination = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)
        if not final_destination:
            raise QgsProcessingException("Final output destination is empty.")

        feedback.pushInfo(f"Resolved final output path: {final_destination}")
        _delete_dataset_if_exists(final_destination)

        if output_crs.isValid() and output_crs != working_crs:
            final_source = processing.run(
                "native:reprojectlayer",
                {
                    "INPUT": smoothed_metric_clean,
                    "TARGET_CRS": output_crs,
                    "OUTPUT": "memory:"
                },
                context=context,
                feedback=feedback
            )["OUTPUT"]
        else:
            final_source = smoothed_metric_clean

        final_output = processing.run(
            "native:savefeatures",
            {
                "INPUT": final_source,
                "OUTPUT": final_destination
            },
            context=context,
            feedback=feedback
        )["OUTPUT"]

        _add_seg_id_any(raw_segments_saved, context)
        _add_seg_id_any(smoothed_metric_path, context)
        _add_seg_id_any(final_output, context)
        feedback.pushInfo("SEG_ID added to shoreline outputs.")

        try:
            meta = {
                "timestamp_utc": datetime.datetime.utcnow().isoformat() + "Z",
                "composite": str(comp_path),
                "green_band_index": green_band_index,
                "green_band_desc": green_desc,
                "swir_band_index": swir_band_index,
                "swir_band_desc": swir_desc,
                "requested_output_crs": output_crs.authid() if output_crs.isValid() else None,
                "working_metric_crs": working_crs.authid() if working_crs.isValid() else None,
                "cellsize_map_units": cs,
                "gaussian_sigma": gaussian_sigma,
                "morph_radius_px": morph_radius,
                "otsu_threshold": float(thresh),
                "water_pixel_count": water_count,
                "metric_pixel_size": float(proj_pixel),
                "min_hole_area": float(min_hole_area),
                "min_poly_area": float(min_poly_area),
                "min_fragment_length": float(min_fragment_length),
                "border_buffer_dist": float(border_buffer_dist),
                "poly_smooth_iterations": int(poly_smooth_iterations),
                "poly_smooth_offset": float(poly_smooth_offset),
                "line_smooth_iterations": int(line_smooth_iterations),
                "line_smooth_offset": float(line_smooth_offset),
                "drop_border_segments": drop_border,
                "paths": {
                    "mndwi": mndwi_raster_path,
                    "binary": binary_raster_path,
                    "shoreline_raw_metric": raw_segments_saved,
                    "shoreline_smoothed_metric": smoothed_metric_path,
                    "final_output": final_output,
                }
            }
            with open(metadata_path, "w", encoding="utf-8") as f:
                json.dump(meta, f, indent=2)
            feedback.pushInfo(f"Metadata written: {metadata_path}")
        except Exception as e:
            feedback.reportError(f"Failed to write metadata JSON: {e}")

        try:
            _queue_layer_for_loading(
                mndwi_raster_path,
                f"{prefix}_MNDWI",
                context,
                group_name="SE+ Outputs",
                sort_key=1
            )

            _queue_layer_for_loading(
                binary_raster_path,
                f"{prefix}_Binary",
                context,
                group_name="SE+ Outputs",
                sort_key=2
            )

            _queue_layer_for_loading(
                raw_segments_saved,
                f"{prefix}_Shoreline_Raw_Metric",
                context,
                group_name="SE+ Outputs",
                sort_key=8
            )

            _queue_layer_for_loading(
                smoothed_metric_path,
                f"{prefix}_Shoreline_Smoothed_Metric",
                context,
                group_name="SE+ Outputs",
                sort_key=9
            )

            _queue_layer_for_loading(
                final_output,
                f"{prefix}_Shoreline_Final",
                context,
                output_name=self.OUTPUT,
                group_name="SE+ Outputs",
                sort_key=10
            )

            feedback.pushInfo("Outputs queued for loading into the QGIS map interface.")
        except Exception as e:
            feedback.reportError(f"Could not queue outputs for map loading: {e}")

        return {self.OUTPUT: final_output}