# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ShorelineSEPlus
                                 A QGIS plugin
 Semi-automated shoreline extraction from multispectral imagery using MNDWI, robust Otsu thresholding, cleanup, smoothing, and Processing outputs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-20
        copyright            : (C) 2026 by Curtis Amo Dwira
        email                : amodwira@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Curtis Amo Dwira'
__date__ = '2026-03-20'
__copyright__ = '(C) 2026 by Curtis Amo Dwira'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtGui import QIcon
from qgis.core import QgsProcessingProvider

from .shoreline_seplus_algorithm import ShorelineSEPlusAlgorithm


class ShorelineSEPlusProvider(QgsProcessingProvider):

    def unload(self):
        pass

    def loadAlgorithms(self):
        self.addAlgorithm(ShorelineSEPlusAlgorithm())

    def id(self):
        return "shoreline_seplus"

    def name(self):
        return "Shoreline SE+"

    def longName(self):
        return self.name()

    def icon(self):
        return QIcon()
